name: Code Safety
run-name: ${{ github.actor }} is checking code quality ðŸ”Ž
on:
  pull_request:
    branches:
      - main

jobs:

  check-formatter:
    name: code-safety/apply-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Enable caching
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - uses: astral-sh/setup-uv@v7

    - run: uv sync --all-extras --dev

    - name: Check formatter
      run: uv run ruff format

  check-linter:
    name: code-safety/check-linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Enable caching
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - uses: astral-sh/setup-uv@v7

    - run: uv sync --all-extras --dev

    - name: Check linter
      run: uv run check

  check-type-safety:
    name: code-safety/check-type-safety
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Enable caching
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - uses: astral-sh/setup-uv@v7

    - run: uv sync --all-extras --dev

    - name: Check type-safety
      run: uv run pyright

  unit-tests:
    name: code-safety/run-unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Enable caching
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - uses: astral-sh/setup-uv@v7

    - run: uv sync --all-extras --dev

    - name: Run unit tests
      run: uv run pytest
